{% set name = "addressable" %}
{% set version = "2.8.4" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 40a88af5285625b7fb14070e550e667d5b0cc91f748068701b4d897cacda4897

build:
  noarch: generic
  number: 0
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-public_suffix >=2.0.2,<5

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'
    - ruby -r {{ name }}/uri -e 'exit 0'
    - ruby -r {{ name }}/template -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Ruby bindings to http://github.com/ry/http-parser and http://github.com/a2800276/http-parser.java

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/sporkmonger/{{ name }}

extra:
  recipe-maintainers:
    - sodre
