{% set name = "addressable" %}
{% set version = "2.8.7" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 462986537cf3735ab5f3c0f557f14155d778f4b43ea4f485a9deb9c8f7c58232

build:
  noarch: generic
  number: 1
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-public_suffix >=2.0.2,<7.0

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'
    - ruby -r {{ name }}/uri -e 'exit 0'
    - ruby -r {{ name }}/template -e 'exit 0'

about:
  home: https://rubygems.org/gems/addressable
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Addressable is an alternative implementation to the URI implementation that is part of Ruby's standard library. It is flexible, offers heuristic parsing, and additionally provides extensive support for IRIs and URI templates.
  doc_url: http://www.rubydoc.info/gems/addressable
  dev_url: https://github.com/sporkmonger/addressable

extra:
  recipe-maintainers:
    - sodre
    - svengiegerich
    - janjagusch
