{% set name = "addressable" %}
{% set version = "2.7.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 5e9b62fe1239091ea9b2893cd00ffe1bcbdd9371f4e1d35fac595c98c5856cbb

build:
  noarch: generic
  number: 1
  script:
    - gem install --norc -l -V --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3
    - rb-public_suffix >=2.0.2,<5

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'
    - ruby -r {{ name }}/uri -e 'exit 0'
    - ruby -r {{ name }}/template -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Ruby bindings to http://github.com/ry/http-parser and http://github.com/a2800276/http-parser.java

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/sporkmonger/{{ name }}

extra:
  recipe-maintainers:
    - sodre
    - svengiegerich
    - janjagusch
