travis:
  secure:
    BINSTAR_TOKEN: VMwRmDS1xWynUJgjf0hfzrdeiZfWPQV4mWaUlDVtlIiW3+xoJ2TG2vB6LaGTmft1V1CqR57at4BFotYkqJfydjZUt8D+btxGnOkdhG4++/KCkGD1/sm76RhczbUVP++dzWSAa41SX0+ueQCV4BEGZjdJE5n0cAx9KHVwRdbs3QLkG2EWfvRb7cdtpMa2jBsWz6wxrkPArBEsTSsjqeUjG7E5UEuge34u1cJzu00dIR8eLIffvRMJqC7DvHungFI3Doixt/7qyIJ+7S20zJbTxR3e1+O4YVEuOXGQNyEtVc4bA4ofEn0OOJXk9B37cnS/epyPVsnNzIKGJyfrv8J+2dzDpFo6NJM9WKikAkcmBWZ9qsWecxELfIYOcRTYAR4aQzB5QoLvznOdTvY42wW1mjD0QXA1u8ICZjDhgCFlZyCvpSZFIfmAvOETgT56J4GcSMY8AIicq5F0L5Ccu1baC1ShS1lFfHDWbG1BpqX+7glHUeruWEhfYY+UutsJRLGbHNsamiedxOrFKozl02sBOuimkm/2GkjD0BqBKwGAK2GXTO9djbCXPjCyUDuCvOeWDG8fz6CYp3G9A73SJwGI4kzsD53A18NqKAWId4AQfMLRJd6U+pvpzf74YcMpsCZ1rIll2rDRfPaEHeuGVd/m5KbLMm3mNLGAAlwJ8n+P1kY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
